name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_push_docker:
    runs-on: ubuntu-latest

    steps:
      - name: Development Code
        uses: actions/checkout@v2

      - run: 'echo "$FIREBASE_CONFIG" > src/firebase.config.json'
        shell: bash
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}

      - run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | head -c7)" >> $GITHUB_ENV

      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}

      - name: Docker Build and Push
        uses: docker/build-push-action@v2.7.0
        with:
          context: ./
          file: Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USER }}/pucpr-react-firebase:latest
            ${{ secrets.DOCKERHUB_USER }}/pucpr-react-firebase:${{ env.GITHUB_SHA_SHORT }}

  build_deploy_firebase:
    if: ${{ false }} # disable for now
    runs-on: ubuntu-latest

    steps:
      - name: Development Code
        uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - run: 'echo "$FIREBASE_CONFIG" > src/firebase.config.json'
        shell: bash
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}

      - run: npm install

      - name: Build React App
        run: npm run build

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
