name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Development Code
        uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - run: 'echo "$FIREBASE_CONFIG" > src/firebase.config.json'
        shell: bash
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}

      - run: npm install

      # - name: Test React App
      #   run: npm run test

      - name: Build React App
        run: npm run build

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      